/**
 * Generated by '@kontent-ai/model-generator@6.5.0'
 */
export const contentTypes = {
    /**
     *  Component  Hero
     */
    component_hero: {
        codename: 'component_hero',
        id: '5de81417-0eb9-4d5b-867e-c594f4b2176b',
        externalId: undefined,
        name: '[Component] Hero',
        elements: {
            /**
             * Cards (modular_content)
             */
            cards: {
                codename: 'cards',
                id: '968cec17-c0ea-444e-8392-3ede882cbcdf',
                externalId: undefined,
                name: 'Cards',
                required: true,
                type: 'modular_content'
            },

            /**
             * Video (asset)
             */
            video: {
                codename: 'video',
                id: '53afaa92-6ab9-437e-9cd1-651415ebe28b',
                externalId: undefined,
                name: 'Video',
                required: true,
                type: 'asset'
            }
        }
    },

    /**
     *  Component  Listing
     */
    component_listing: {
        codename: 'component_listing',
        id: 'af79ec49-6170-4779-a096-dce846f7e8ef',
        externalId: undefined,
        name: '[Component] Listing',
        elements: {
            /**
             * Data (modular_content)
             */
            data: {
                codename: 'data',
                id: '4dd82cc5-307a-44f3-bc0c-cfb4aa3f2664',
                externalId: undefined,
                name: 'Data',
                required: true,
                type: 'modular_content'
            },

            /**
             * Title (text)
             */
            title: {
                codename: 'title',
                id: '823d9411-ce09-4a51-bf6a-352c5ac83da1',
                externalId: undefined,
                name: 'Title',
                required: true,
                type: 'text'
            }
        }
    },

    /**
     *  Component  Newsletter CTA
     */
    component_newsletter_cta: {
        codename: 'component_newsletter_cta',
        id: '9adf85e2-8161-47f9-b07c-8800cbb0e2f2',
        externalId: undefined,
        name: '[Component] Newsletter CTA',
        elements: {}
    },

    /**
     *  Component  Text Section
     */
    component_text_section: {
        codename: 'component_text_section',
        id: '816aae69-2d8a-4def-ba3e-10247d45d07b',
        externalId: undefined,
        name: '[Component] Text Section',
        elements: {
            /**
             * Text (rich_text)
             */
            text: {
                codename: 'text',
                id: '7a18f4b4-977a-45ba-9a46-0dbb05fa3140',
                externalId: undefined,
                name: 'Text',
                required: false,
                type: 'rich_text'
            },

            /**
             * Title (text)
             */
            title: {
                codename: 'title',
                id: 'cb24f4f2-ea62-4c8e-84f2-559275295f44',
                externalId: undefined,
                name: 'Title',
                required: false,
                type: 'text'
            }
        }
    },

    /**
     * Aircraft
     */
    aircraft: {
        codename: 'aircraft',
        id: '2440feae-9261-42ae-8369-f1c662c6233f',
        externalId: undefined,
        name: 'Aircraft',
        elements: {
            /**
             * ID (text)
             */
            id: {
                codename: 'id',
                id: '1b7ee5bd-fe02-4209-9e43-681b7b054376',
                externalId: undefined,
                name: 'ID',
                required: false,
                type: 'text'
            },

            /**
             * Type (multiple_choice)
             */
            type: {
                codename: 'type',
                id: '0c3a2dce-da7a-4b36-a96a-db65baeaa3fb',
                externalId: undefined,
                name: 'Type',
                required: false,
                type: 'multiple_choice',
                options: {
                    b737800: {
                        name: 'B737',
                        id: 'bd3b399c-8ddc-4e61-8362-093838d046fb',
                        codename: 'b737800',
                        externalId: undefined
                    },
                    b737max: {
                        name: 'B737 MAX',
                        id: 'f295bc8e-91a4-45da-b44e-b6d7cee24e39',
                        codename: 'b737max',
                        externalId: undefined
                    }
                }
            }
        }
    },

    /**
     * Airport
     */
    airport: {
        codename: 'airport',
        id: 'a244a679-fce7-4257-b851-3b65d369a7e9',
        externalId: undefined,
        name: 'Airport',
        elements: {
            /**
             * Code (text)
             */
            code: {
                codename: 'code',
                id: '3134abb7-d14c-4f1a-be7e-320ab14fbe67',
                externalId: undefined,
                name: 'Code',
                required: false,
                type: 'text'
            },

            /**
             * Title (text)
             */
            title: {
                codename: 'title',
                id: 'ba8687df-4db9-4927-9cb7-d3c4ceb1f8be',
                externalId: undefined,
                name: 'Title',
                required: false,
                type: 'text'
            }
        }
    },

    /**
     * Destination
     */
    destination: {
        codename: 'destination',
        id: 'c192652d-0053-4e9c-8299-b1407335e466',
        externalId: undefined,
        name: 'Destination',
        elements: {
            /**
             * Photo (asset)
             */
            photo: {
                codename: 'photo',
                id: 'a7d3da0f-a425-4746-b98b-07fdb3b85556',
                externalId: undefined,
                name: 'Photo',
                required: true,
                type: 'asset'
            },

            /**
             * Text (rich_text)
             */
            text: {
                codename: 'text',
                id: '0ebf0bd3-03dc-486b-b3c7-fc9e8a139bba',
                externalId: undefined,
                name: 'Text',
                required: true,
                type: 'rich_text'
            },

            /**
             * Title (text)
             */
            title: {
                codename: 'title',
                id: 'cf567e56-40a1-45a4-8458-1efeaa0281bc',
                externalId: undefined,
                name: 'Title',
                required: true,
                type: 'text'
            }
        }
    },

    /**
     * Flight
     */
    flight: {
        codename: 'flight',
        id: 'd237c1f1-d954-4890-9d33-818ce4cf2f9c',
        externalId: undefined,
        name: 'Flight',
        elements: {
            /**
             * Aircraft (modular_content)
             */
            aircraft: {
                codename: 'aircraft',
                id: '2088c738-5e80-44e7-8e98-53bcdae5fd5d',
                externalId: undefined,
                name: 'Aircraft',
                required: true,
                type: 'modular_content'
            },

            /**
             * Arrival (date_time)
             */
            arrival: {
                codename: 'arrival',
                id: '7c8b4831-40c0-4886-9aa4-24916541b2f9',
                externalId: undefined,
                name: 'Arrival',
                required: true,
                type: 'date_time'
            },

            /**
             * Departure (date_time)
             */
            departure: {
                codename: 'departure',
                id: 'ae398974-1288-4913-8d6c-5cd0e32ff1eb',
                externalId: undefined,
                name: 'Departure',
                required: true,
                type: 'date_time'
            },

            /**
             * Destination (modular_content)
             */
            destination: {
                codename: 'destination',
                id: 'f0f5a988-42af-47e6-b94d-019d448694c5',
                externalId: undefined,
                name: 'Destination',
                required: true,
                type: 'modular_content'
            },

            /**
             * Origin (modular_content)
             */
            origin: {
                codename: 'origin',
                id: '332701a3-9b96-4f49-bf3b-0bce92026cbe',
                externalId: undefined,
                name: 'Origin',
                required: true,
                type: 'modular_content'
            },

            /**
             * Statuses (modular_content)
             */
            statuses: {
                codename: 'statuses',
                id: 'c87c120a-ac99-4a32-8572-2052073a98be',
                externalId: undefined,
                name: 'Statuses',
                required: false,
                type: 'modular_content'
            }
        }
    },

    /**
     * Hero Card
     */
    hero_card: {
        codename: 'hero_card',
        id: '76f79e81-a139-4ece-9f18-2709f155fa0d',
        externalId: undefined,
        name: 'Hero Card',
        elements: {
            /**
             * Text (rich_text)
             */
            text: {
                codename: 'text',
                id: '2fb64b02-85e2-41d5-a5aa-495b0b37ee41',
                externalId: undefined,
                name: 'Text',
                required: false,
                type: 'rich_text'
            },

            /**
             * Title (text)
             */
            title: {
                codename: 'title',
                id: 'e53b24da-ccb9-4dab-9ee3-298821aea890',
                externalId: undefined,
                name: 'Title',
                required: false,
                type: 'text'
            }
        }
    },

    /**
     * Status
     */
    status: {
        codename: 'status',
        id: 'ed333737-d3f2-44d8-9752-aeffcc3373f6',
        externalId: undefined,
        name: 'Status',
        elements: {
            /**
             * Message (text)
             */
            message: {
                codename: 'message',
                id: '2373d1ed-3ea6-4d25-8913-3d1b56701f94',
                externalId: undefined,
                name: 'Message',
                required: false,
                type: 'text'
            },

            /**
             * Severity (multiple_choice)
             */
            severity: {
                codename: 'severity',
                id: '85aacdcb-e64c-4e3a-ab3a-ef7d6534f84e',
                externalId: undefined,
                name: 'Severity',
                required: false,
                type: 'multiple_choice',
                options: {
                    info: {
                        name: 'Info',
                        id: '23daf0f8-31e5-4bf4-b85d-c20128dccba2',
                        codename: 'info',
                        externalId: undefined
                    },
                    problem: {
                        name: 'Problem',
                        id: '6dd627ed-6307-456a-a6da-8a7076fc447b',
                        codename: 'problem',
                        externalId: undefined
                    },
                    cancellation: {
                        name: 'Cancellation',
                        id: '9ef52e9d-6da7-40fb-86ab-a71890cbb96d',
                        codename: 'cancellation',
                        externalId: undefined
                    }
                }
            }
        }
    }
} as const;
