/**
 * Generated by '@kontent-ai/model-generator@6.5.0'
 */
export const roles = {
    /**
     * Project manager
     */
    projectManager: {
        codename: 'project-manager',
        id: '6f2cfb98-447c-4d88-a70c-43a6da34f7bd',
        name: 'Project manager'
    }
} as const;
