import { type IContentItem, type Elements } from '@kontent-ai/delivery-sdk';
/**
 * Generated by '@kontent-ai/model-generator@6.5.0'
 *
 * Aircraft
 * Id: 2440feae-9261-42ae-8369-f1c662c6233f
 * Codename: aircraft
 */
export type AircraftModel = IContentItem<{
    /**
     * ID (text)
     * Required: false
     * Id: 1b7ee5bd-fe02-4209-9e43-681b7b054376
     * Codename: id
     */
    id: Elements.TextElement;

    /**
     * Type (multiple_choice)
     * Required: false
     * Id: 0c3a2dce-da7a-4b36-a96a-db65baeaa3fb
     * Codename: type
     */
    type: Elements.MultipleChoiceElement;
}>;
