import { type IContentItem, type Elements } from '@kontent-ai/delivery-sdk';
/**
 * Generated by '@kontent-ai/model-generator@6.5.0'
 *
 * Airport
 * Id: a244a679-fce7-4257-b851-3b65d369a7e9
 * Codename: airport
 */
export type AirportModel = IContentItem<{
    /**
     * Code (text)
     * Required: false
     * Id: 3134abb7-d14c-4f1a-be7e-320ab14fbe67
     * Codename: code
     */
    code: Elements.TextElement;

    /**
     * Title (text)
     * Required: false
     * Id: ba8687df-4db9-4927-9cb7-d3c4ceb1f8be
     * Codename: title
     */
    title: Elements.TextElement;
}>;
