import { type IContentItem, type Elements } from '@kontent-ai/delivery-sdk';
import { type HeroCardModel } from './HeroCardModel';

/**
 * Generated by '@kontent-ai/model-generator@6.5.0'
 *
 * [Component] Hero
 * Id: 5de81417-0eb9-4d5b-867e-c594f4b2176b
 * Codename: component_hero
 */
export type ComponentHeroModel = IContentItem<{
    /**
     * Cards (modular_content)
     * Required: true
     * Id: 968cec17-c0ea-444e-8392-3ede882cbcdf
     * Codename: cards
     */
    cards: Elements.LinkedItemsElement<HeroCardModel>;

    /**
     * Video (asset)
     * Required: true
     * Id: 53afaa92-6ab9-437e-9cd1-651415ebe28b
     * Codename: video
     */
    video: Elements.AssetsElement;
}>;
