import { type IContentItem, type Elements } from '@kontent-ai/delivery-sdk';
/**
 * Generated by '@kontent-ai/model-generator@6.5.0'
 *
 * [Component] Text Section
 * Id: 816aae69-2d8a-4def-ba3e-10247d45d07b
 * Codename: component_text_section
 */
export type ComponentTextSectionModel = IContentItem<{
    /**
     * Text (rich_text)
     * Required: false
     * Id: 7a18f4b4-977a-45ba-9a46-0dbb05fa3140
     * Codename: text
     */
    text: Elements.RichTextElement;

    /**
     * Title (text)
     * Required: false
     * Id: cb24f4f2-ea62-4c8e-84f2-559275295f44
     * Codename: title
     */
    title: Elements.TextElement;
}>;
