import { type IContentItem } from '@kontent-ai/delivery-sdk';
/**
 * Generated by '@kontent-ai/model-generator@6.5.0'
 *
 * [Component] Newsletter CTA
 * Id: 9adf85e2-8161-47f9-b07c-8800cbb0e2f2
 * Codename: component_newsletter_cta
 */
export type ComponentNewsletterCtaModel = IContentItem<{}>;
