import { type IContentItem, type Elements } from '@kontent-ai/delivery-sdk';
import { type DestinationModel } from './DestinationModel';

/**
 * Generated by '@kontent-ai/model-generator@6.5.0'
 *
 * [Component] Listing
 * Id: af79ec49-6170-4779-a096-dce846f7e8ef
 * Codename: component_listing
 */
export type ComponentListingModel = IContentItem<{
    /**
     * Data (modular_content)
     * Required: true
     * Id: 4dd82cc5-307a-44f3-bc0c-cfb4aa3f2664
     * Codename: data
     */
    data: Elements.LinkedItemsElement<DestinationModel>;

    /**
     * Title (text)
     * Required: true
     * Id: 823d9411-ce09-4a51-bf6a-352c5ac83da1
     * Codename: title
     */
    title: Elements.TextElement;
}>;
