import { type IContentItem, type Elements } from '@kontent-ai/delivery-sdk';
/**
 * Generated by '@kontent-ai/model-generator@6.5.0'
 *
 * Destination
 * Id: c192652d-0053-4e9c-8299-b1407335e466
 * Codename: destination
 */
export type DestinationModel = IContentItem<{
    /**
     * Photo (asset)
     * Required: true
     * Id: a7d3da0f-a425-4746-b98b-07fdb3b85556
     * Codename: photo
     */
    photo: Elements.AssetsElement;

    /**
     * Text (rich_text)
     * Required: true
     * Id: 0ebf0bd3-03dc-486b-b3c7-fc9e8a139bba
     * Codename: text
     */
    text: Elements.RichTextElement;

    /**
     * Title (text)
     * Required: true
     * Id: cf567e56-40a1-45a4-8458-1efeaa0281bc
     * Codename: title
     */
    title: Elements.TextElement;
}>;
