import { type IContentItem, type Elements } from '@kontent-ai/delivery-sdk';
import { type AircraftModel } from './AircraftModel';
import { type AirportModel } from './AirportModel';
import { type StatusModel } from './StatusModel';

/**
 * Generated by '@kontent-ai/model-generator@6.5.0'
 *
 * Flight
 * Id: d237c1f1-d954-4890-9d33-818ce4cf2f9c
 * Codename: flight
 */
export type FlightModel = IContentItem<{
    /**
     * Aircraft (modular_content)
     * Required: true
     * Id: 2088c738-5e80-44e7-8e98-53bcdae5fd5d
     * Codename: aircraft
     */
    aircraft: Elements.LinkedItemsElement<AircraftModel>;

    /**
     * Arrival (date_time)
     * Required: true
     * Id: 7c8b4831-40c0-4886-9aa4-24916541b2f9
     * Codename: arrival
     */
    arrival: Elements.DateTimeElement;

    /**
     * Departure (date_time)
     * Required: true
     * Id: ae398974-1288-4913-8d6c-5cd0e32ff1eb
     * Codename: departure
     */
    departure: Elements.DateTimeElement;

    /**
     * Destination (modular_content)
     * Required: true
     * Id: f0f5a988-42af-47e6-b94d-019d448694c5
     * Codename: destination
     */
    destination: Elements.LinkedItemsElement<AirportModel>;

    /**
     * Origin (modular_content)
     * Required: true
     * Id: 332701a3-9b96-4f49-bf3b-0bce92026cbe
     * Codename: origin
     */
    origin: Elements.LinkedItemsElement<AirportModel>;

    /**
     * Statuses (modular_content)
     * Required: false
     * Id: c87c120a-ac99-4a32-8572-2052073a98be
     * Codename: statuses
     */
    statuses: Elements.LinkedItemsElement<StatusModel>;
}>;
