import { type IContentItem, type Elements } from '@kontent-ai/delivery-sdk';
/**
 * Generated by '@kontent-ai/model-generator@6.5.0'
 *
 * Hero Card
 * Id: 76f79e81-a139-4ece-9f18-2709f155fa0d
 * Codename: hero_card
 */
export type HeroCardModel = IContentItem<{
    /**
     * Text (rich_text)
     * Required: false
     * Id: 2fb64b02-85e2-41d5-a5aa-495b0b37ee41
     * Codename: text
     */
    text: Elements.RichTextElement;

    /**
     * Title (text)
     * Required: false
     * Id: e53b24da-ccb9-4dab-9ee3-298821aea890
     * Codename: title
     */
    title: Elements.TextElement;
}>;
