import { type IContentItem, type Elements } from '@kontent-ai/delivery-sdk';
/**
 * Generated by '@kontent-ai/model-generator@6.5.0'
 *
 * Status
 * Id: ed333737-d3f2-44d8-9752-aeffcc3373f6
 * Codename: status
 */
export type StatusModel = IContentItem<{
    /**
     * Message (text)
     * Required: false
     * Id: 2373d1ed-3ea6-4d25-8913-3d1b56701f94
     * Codename: message
     */
    message: Elements.TextElement;

    /**
     * Severity (multiple_choice)
     * Required: false
     * Id: 85aacdcb-e64c-4e3a-ab3a-ef7d6534f84e
     * Codename: severity
     */
    severity: Elements.MultipleChoiceElement;
}>;
